/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    microsites: Microsite;
    'microsite-settings': MicrositeSetting;
    pages: Page;
    posts: Post;
    events: Event;
    visitors: Visitor;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    microsites: MicrositesSelect<false> | MicrositesSelect<true>;
    'microsite-settings': MicrositeSettingsSelect<false> | MicrositeSettingsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    theme: Theme;
    'main-site': MainSite;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    'main-site': MainSiteSelect<false> | MainSiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each fair brand (e.g. ECGE 2026). Posts, pages and events are assigned to a microsite and appear on that fair’s public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "microsites".
 */
export interface Microsite {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  isActive?: boolean | null;
  /**
   * Public Next.js origin in development. Leave blank to use http://{slug}.{ROOT_DOMAIN} or /m/{slug} locally.
   */
  devUrl?: string | null;
  /**
   * Optional override. Leave blank to use https://{slug}.{ROOT_DOMAIN} from env ROOT_DOMAIN.
   */
  productionUrl?: string | null;
  crmEventName?: string | null;
  /**
   * Prefer setting this on Microsite Settings. Fallback if settings doc is missing.
   */
  crmEventId?: string | null;
  /**
   * Prefer Theme on Microsite Settings. Used only if settings theme is empty.
   */
  primaryColor?: string | null;
  secondaryColor?: string | null;
  darkColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One settings document per microsite — contact details and hero/footer copy for the public fair site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "microsite-settings".
 */
export interface MicrositeSetting {
  id: number;
  /**
   * Admin label, e.g. "ECGE 2026 site settings".
   */
  label: string;
  /**
   * Assigned automatically from the microsite switcher in the admin sidebar.
   */
  microsite?: (number | null) | Microsite;
  crmEventName?: string | null;
  /**
   * Search and select the sales-CRM event that supplies booths and floor plans.
   */
  crmEventId?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  /**
   * Small line above the hero headline.
   */
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  footerNote?: string | null;
  /**
   * Used on visitor PDF tickets and email branding. Prefer a transparent PNG.
   */
  logo?: (number | null) | Media;
  /**
   * 4–8 digit PIN for the public /check-in kiosk. Leave empty to disable kiosk check-in.
   */
  checkInPin?: string | null;
  /**
   * Colors and typography for the public microsite. Applied as CSS variables on every page.
   */
  theme?: {
    /**
     * Brand green / sustainability
     */
    primary?: string | null;
    secondary?: string | null;
    dark?: string | null;
    font?:
      | (
          | 'Inter'
          | 'Arial'
          | 'Helvetica'
          | 'Verdana'
          | 'Tahoma'
          | 'Trebuchet MS'
          | 'Georgia'
          | 'Times New Roman'
          | 'Garamond'
          | 'Palatino Linotype'
          | 'Courier New'
          | 'Lucida Sans'
          | 'Segoe UI'
          | 'Roboto'
          | 'Open Sans'
          | 'Montserrat'
          | 'Poppins'
          | 'Lato'
        )
      | null;
    homeBgStart?: string | null;
    homeBgMid?: string | null;
    homeBgEnd?: string | null;
    headerBg?: string | null;
    calendarBgStart?: string | null;
    calendarBgMid?: string | null;
    calendarBgEnd?: string | null;
    calendarGlowPrimaryColor?: string | null;
    calendarGlowSecondaryColor?: string | null;
  };
  /**
   * Mega-menu groups for the public microsite. Lead and item links must pick existing pages in this microsite.
   */
  navigation?:
    | {
        /**
         * Stable id, e.g. about, visit, exhibit.
         */
        key: string;
        titleSq: string;
        titleEn: string;
        leadSq: string;
        leadEn: string;
        /**
         * Page opened when the group lead is clicked.
         */
        leadPage: number | Page;
        items?:
          | {
              /**
               * Select an existing page in this microsite.
               */
              page: number | Page;
              labelSq: string;
              labelEn: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null)
              | ({
                  relationTo: 'events';
                  value: number | Event;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | GalleryBlock | BannerBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Assigned automatically from the microsite switcher in the admin sidebar.
   */
  microsite?: (number | null) | Microsite;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * Assigned automatically from the microsite switcher in the admin sidebar.
   */
  microsite?: (number | null) | Microsite;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  eventDate: string;
  location?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedEvents?: (number | Event)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * Assigned automatically from the microsite switcher in the admin sidebar.
   */
  microsite?: (number | null) | Microsite;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  style: 'slideshow' | 'grid';
  /**
   * Seconds between slides. Set to 0 to disable autoplay.
   */
  autoplaySeconds?: number | null;
  slides: {
    image: number | Media;
    caption?: string | null;
    /**
     * Optional URL when the slide is clicked.
     */
    link?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Visitor registrations and entrance tickets for the active microsite / exhibition.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: number;
  /**
   * Assigned automatically from the microsite switcher in the admin sidebar.
   */
  microsite?: (number | null) | Microsite;
  /**
   * CRM exhibition event snapshot at registration time.
   */
  crmEventId?: string | null;
  crmEventName?: string | null;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  jobTitle?: string | null;
  country?: string | null;
  /**
   * Opaque token used in QR codes and ticket URLs.
   */
  ticketToken: string;
  status: 'registered' | 'checked_in' | 'cancelled';
  checkedInAt?: string | null;
  /**
   * User id or "kiosk".
   */
  checkedInBy?: string | null;
  eventTitle?: string | null;
  eventDates?: string | null;
  eventLocation?: string | null;
  emailSentAt?: string | null;
  emailError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    url?: string | null;
  };
  /**
   * Assigned automatically from the microsite switcher in the admin sidebar.
   */
  microsite?: (number | null) | Microsite;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  microsite?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'microsites';
        value: number | Microsite;
      } | null)
    | ({
        relationTo: 'microsite-settings';
        value: number | MicrositeSetting;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'visitors';
        value: number | Visitor;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "microsites_select".
 */
export interface MicrositesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  isActive?: T;
  devUrl?: T;
  productionUrl?: T;
  crmEventName?: T;
  crmEventId?: T;
  primaryColor?: T;
  secondaryColor?: T;
  darkColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "microsite-settings_select".
 */
export interface MicrositeSettingsSelect<T extends boolean = true> {
  label?: T;
  microsite?: T;
  crmEventName?: T;
  crmEventId?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  footerNote?: T;
  logo?: T;
  checkInPin?: T;
  theme?:
    | T
    | {
        primary?: T;
        secondary?: T;
        dark?: T;
        font?: T;
        homeBgStart?: T;
        homeBgMid?: T;
        homeBgEnd?: T;
        headerBg?: T;
        calendarBgStart?: T;
        calendarBgMid?: T;
        calendarBgEnd?: T;
        calendarGlowPrimaryColor?: T;
        calendarGlowSecondaryColor?: T;
      };
  navigation?:
    | T
    | {
        key?: T;
        titleSq?: T;
        titleEn?: T;
        leadSq?: T;
        leadEn?: T;
        leadPage?: T;
        items?:
          | T
          | {
              page?: T;
              labelSq?: T;
              labelEn?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  microsite?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  style?: T;
  autoplaySeconds?: T;
  slides?:
    | T
    | {
        image?: T;
        caption?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  microsite?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  eventDate?: T;
  location?: T;
  content?: T;
  relatedEvents?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  microsite?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  microsite?: T;
  crmEventId?: T;
  crmEventName?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  jobTitle?: T;
  country?: T;
  ticketToken?: T;
  status?: T;
  checkedInAt?: T;
  checkedInBy?: T;
  eventTitle?: T;
  eventDates?: T;
  eventLocation?: T;
  emailSentAt?: T;
  emailError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  microsite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  microsite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the look and feel of the site — colors, typography, branding and shape.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Primary logo, shown in the header.
   */
  logo?: (number | null) | Media;
  /**
   * Optional alternate logo for dark mode.
   */
  logoDark?: (number | null) | Media;
  /**
   * The color mode new visitors see first.
   */
  defaultMode?: ('light' | 'dark' | 'system') | null;
  /**
   * Corner rounding applied to buttons, cards and inputs.
   */
  radius?: ('none' | 'small' | 'medium' | 'large' | 'xlarge') | null;
  /**
   * Keep the header pinned to the top while scrolling.
   */
  stickyHeader?: boolean | null;
  /**
   * Render image heroes (home & posts) in dark mode with white text. Turn off to follow the page theme colors instead.
   */
  heroDarkOverlay?: boolean | null;
  fontSans?: ('geist' | 'sans' | 'serif' | 'mono') | null;
  fontHeading?: ('geist' | 'sans' | 'serif' | 'mono') | null;
  fontMono?: ('geist' | 'sans' | 'serif' | 'mono') | null;
  headingWeight?: ('normal' | 'medium' | 'semibold' | 'bold') | null;
  baseFontSize?: ('small' | 'medium' | 'large' | 'xlarge') | null;
  lineHeight?: ('tight' | 'normal' | 'relaxed') | null;
  lightColors?: {
    background?: string | null;
    foreground?: string | null;
    primary?: string | null;
    primaryForeground?: string | null;
    secondary?: string | null;
    secondaryForeground?: string | null;
    accent?: string | null;
    accentForeground?: string | null;
    muted?: string | null;
    mutedForeground?: string | null;
    card?: string | null;
    cardForeground?: string | null;
    border?: string | null;
  };
  darkColors?: {
    background?: string | null;
    foreground?: string | null;
    primary?: string | null;
    primaryForeground?: string | null;
    secondary?: string | null;
    secondaryForeground?: string | null;
    accent?: string | null;
    accentForeground?: string | null;
    muted?: string | null;
    mutedForeground?: string | null;
    card?: string | null;
    cardForeground?: string | null;
    border?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Corporate i-exhibitions.com homepage — every section, platform link, news card, video, and theme color.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-site".
 */
export interface MainSite {
  id: number;
  /**
   * Brand palette (default: 80% white / 15% black / 5% IX orange).
   */
  theme?: {
    black?: string | null;
    white?: string | null;
    accent?: string | null;
    grey?: string | null;
    soft?: string | null;
    film?: string | null;
    muted?: string | null;
  };
  navAboutEn?: string | null;
  navAboutSq?: string | null;
  navEventsEn?: string | null;
  navEventsSq?: string | null;
  navCultureEn?: string | null;
  navCultureSq?: string | null;
  navNewsEn?: string | null;
  navNewsSq?: string | null;
  navContactEn?: string | null;
  navContactSq?: string | null;
  heroEyebrowEn?: string | null;
  heroEyebrowSq?: string | null;
  heroTitleEn?: string | null;
  heroTitleSq?: string | null;
  heroBrandEn?: string | null;
  heroBrandSq?: string | null;
  heroBodyEn?: string | null;
  heroBodySq?: string | null;
  heroCtaPrimaryEn?: string | null;
  heroCtaPrimarySq?: string | null;
  heroCtaSecondaryEn?: string | null;
  heroCtaSecondarySq?: string | null;
  heroImage?: (number | null) | Media;
  heroCaptionEn?: string | null;
  heroCaptionSq?: string | null;
  platformsEyebrowEn?: string | null;
  platformsEyebrowSq?: string | null;
  platformsHeadingEn?: string | null;
  platformsHeadingSq?: string | null;
  platformsIntroEn?: string | null;
  platformsIntroSq?: string | null;
  platformsSeeAllEn?: string | null;
  platformsSeeAllSq?: string | null;
  /**
   * Fairs / platforms. “Microsite” → /m/{slug} (or production URL). “External” → custom URL (e.g. Future2Tech).
   */
  platforms?:
    | {
        titleEn: string;
        titleSq: string;
        subtitleEn?: string | null;
        subtitleSq?: string | null;
        blurbEn?: string | null;
        blurbSq?: string | null;
        logo?: (number | null) | Media;
        linkType: 'microsite' | 'external';
        microsite?: (number | null) | Microsite;
        externalUrl?: string | null;
        /**
         * Marquee word, e.g. TOURISM
         */
        tickerLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        labelEn: string;
        labelSq: string;
        id?: string | null;
      }[]
    | null;
  storyEyebrowEn?: string | null;
  storyEyebrowSq?: string | null;
  storyTitleEn?: string | null;
  storyTitleSq?: string | null;
  storyBodyEn?: string | null;
  storyBodySq?: string | null;
  storyCtaEn?: string | null;
  storyCtaSq?: string | null;
  storyBadgeEn?: string | null;
  storyBadgeSq?: string | null;
  storyImage?: (number | null) | Media;
  cultureEyebrowEn?: string | null;
  cultureEyebrowSq?: string | null;
  cultureTitleBeforeEn?: string | null;
  cultureTitleBeforeSq?: string | null;
  cultureTitleAccentEn?: string | null;
  cultureTitleAccentSq?: string | null;
  cultureBodyEn?: string | null;
  cultureBodySq?: string | null;
  cultureMeetTeamEn?: string | null;
  cultureMeetTeamSq?: string | null;
  /**
   * “What We Stand For” principles
   */
  cultureValues?:
    | {
        titleEn: string;
        titleSq: string;
        bodyEn?: string | null;
        bodySq?: string | null;
        id?: string | null;
      }[]
    | null;
  missionTitleEn?: string | null;
  missionTitleSq?: string | null;
  missionBodyEn?: string | null;
  missionBodySq?: string | null;
  team?:
    | {
        name: string;
        roleEn: string;
        roleSq: string;
        /**
         * Avatar initials, e.g. ES
         */
        initials?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  servicesEyebrowEn?: string | null;
  servicesEyebrowSq?: string | null;
  servicesHeadingEn?: string | null;
  servicesHeadingSq?: string | null;
  services?:
    | {
        titleEn: string;
        titleSq: string;
        bodyEn?: string | null;
        bodySq?: string | null;
        ctaEn?: string | null;
        ctaSq?: string | null;
        /**
         * Anchor or URL, e.g. #contact
         */
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  filmEyebrowEn?: string | null;
  filmEyebrowSq?: string | null;
  filmTitleEn?: string | null;
  filmTitleSq?: string | null;
  filmMetaEn?: string | null;
  filmMetaSq?: string | null;
  filmUrl?: string | null;
  newsEyebrowEn?: string | null;
  newsEyebrowSq?: string | null;
  newsHeadingEn?: string | null;
  newsHeadingSq?: string | null;
  newsAllLabelEn?: string | null;
  newsAllLabelSq?: string | null;
  newsItems?:
    | {
        categoryEn?: string | null;
        categorySq?: string | null;
        titleEn: string;
        titleSq: string;
        bodyEn?: string | null;
        bodySq?: string | null;
        image?: (number | null) | Media;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube links (cover + click-through)
   */
  videos?:
    | {
        titleEn: string;
        titleSq: string;
        youtubeUrl: string;
        cover?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctaEyebrowEn?: string | null;
  ctaEyebrowSq?: string | null;
  ctaTitleEn?: string | null;
  ctaTitleSq?: string | null;
  ctaButtonEn?: string | null;
  ctaButtonSq?: string | null;
  footerTaglineEn?: string | null;
  footerTaglineSq?: string | null;
  footerExploreEn?: string | null;
  footerExploreSq?: string | null;
  footerPlatformsEn?: string | null;
  footerPlatformsSq?: string | null;
  footerConnectEn?: string | null;
  footerConnectSq?: string | null;
  copyrightEn?: string | null;
  copyrightSq?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  addressEn?: string | null;
  addressSq?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  logo?: T;
  logoDark?: T;
  defaultMode?: T;
  radius?: T;
  stickyHeader?: T;
  heroDarkOverlay?: T;
  fontSans?: T;
  fontHeading?: T;
  fontMono?: T;
  headingWeight?: T;
  baseFontSize?: T;
  lineHeight?: T;
  lightColors?:
    | T
    | {
        background?: T;
        foreground?: T;
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        accent?: T;
        accentForeground?: T;
        muted?: T;
        mutedForeground?: T;
        card?: T;
        cardForeground?: T;
        border?: T;
      };
  darkColors?:
    | T
    | {
        background?: T;
        foreground?: T;
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        accent?: T;
        accentForeground?: T;
        muted?: T;
        mutedForeground?: T;
        card?: T;
        cardForeground?: T;
        border?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-site_select".
 */
export interface MainSiteSelect<T extends boolean = true> {
  theme?:
    | T
    | {
        black?: T;
        white?: T;
        accent?: T;
        grey?: T;
        soft?: T;
        film?: T;
        muted?: T;
      };
  navAboutEn?: T;
  navAboutSq?: T;
  navEventsEn?: T;
  navEventsSq?: T;
  navCultureEn?: T;
  navCultureSq?: T;
  navNewsEn?: T;
  navNewsSq?: T;
  navContactEn?: T;
  navContactSq?: T;
  heroEyebrowEn?: T;
  heroEyebrowSq?: T;
  heroTitleEn?: T;
  heroTitleSq?: T;
  heroBrandEn?: T;
  heroBrandSq?: T;
  heroBodyEn?: T;
  heroBodySq?: T;
  heroCtaPrimaryEn?: T;
  heroCtaPrimarySq?: T;
  heroCtaSecondaryEn?: T;
  heroCtaSecondarySq?: T;
  heroImage?: T;
  heroCaptionEn?: T;
  heroCaptionSq?: T;
  platformsEyebrowEn?: T;
  platformsEyebrowSq?: T;
  platformsHeadingEn?: T;
  platformsHeadingSq?: T;
  platformsIntroEn?: T;
  platformsIntroSq?: T;
  platformsSeeAllEn?: T;
  platformsSeeAllSq?: T;
  platforms?:
    | T
    | {
        titleEn?: T;
        titleSq?: T;
        subtitleEn?: T;
        subtitleSq?: T;
        blurbEn?: T;
        blurbSq?: T;
        logo?: T;
        linkType?: T;
        microsite?: T;
        externalUrl?: T;
        tickerLabel?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        labelEn?: T;
        labelSq?: T;
        id?: T;
      };
  storyEyebrowEn?: T;
  storyEyebrowSq?: T;
  storyTitleEn?: T;
  storyTitleSq?: T;
  storyBodyEn?: T;
  storyBodySq?: T;
  storyCtaEn?: T;
  storyCtaSq?: T;
  storyBadgeEn?: T;
  storyBadgeSq?: T;
  storyImage?: T;
  cultureEyebrowEn?: T;
  cultureEyebrowSq?: T;
  cultureTitleBeforeEn?: T;
  cultureTitleBeforeSq?: T;
  cultureTitleAccentEn?: T;
  cultureTitleAccentSq?: T;
  cultureBodyEn?: T;
  cultureBodySq?: T;
  cultureMeetTeamEn?: T;
  cultureMeetTeamSq?: T;
  cultureValues?:
    | T
    | {
        titleEn?: T;
        titleSq?: T;
        bodyEn?: T;
        bodySq?: T;
        id?: T;
      };
  missionTitleEn?: T;
  missionTitleSq?: T;
  missionBodyEn?: T;
  missionBodySq?: T;
  team?:
    | T
    | {
        name?: T;
        roleEn?: T;
        roleSq?: T;
        initials?: T;
        photo?: T;
        id?: T;
      };
  servicesEyebrowEn?: T;
  servicesEyebrowSq?: T;
  servicesHeadingEn?: T;
  servicesHeadingSq?: T;
  services?:
    | T
    | {
        titleEn?: T;
        titleSq?: T;
        bodyEn?: T;
        bodySq?: T;
        ctaEn?: T;
        ctaSq?: T;
        ctaHref?: T;
        id?: T;
      };
  filmEyebrowEn?: T;
  filmEyebrowSq?: T;
  filmTitleEn?: T;
  filmTitleSq?: T;
  filmMetaEn?: T;
  filmMetaSq?: T;
  filmUrl?: T;
  newsEyebrowEn?: T;
  newsEyebrowSq?: T;
  newsHeadingEn?: T;
  newsHeadingSq?: T;
  newsAllLabelEn?: T;
  newsAllLabelSq?: T;
  newsItems?:
    | T
    | {
        categoryEn?: T;
        categorySq?: T;
        titleEn?: T;
        titleSq?: T;
        bodyEn?: T;
        bodySq?: T;
        image?: T;
        href?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        titleEn?: T;
        titleSq?: T;
        youtubeUrl?: T;
        cover?: T;
        id?: T;
      };
  ctaEyebrowEn?: T;
  ctaEyebrowSq?: T;
  ctaTitleEn?: T;
  ctaTitleSq?: T;
  ctaButtonEn?: T;
  ctaButtonSq?: T;
  footerTaglineEn?: T;
  footerTaglineSq?: T;
  footerExploreEn?: T;
  footerExploreSq?: T;
  footerPlatformsEn?: T;
  footerPlatformsSq?: T;
  footerConnectEn?: T;
  footerConnectSq?: T;
  copyrightEn?: T;
  copyrightSq?: T;
  contactEmail?: T;
  contactPhone?: T;
  addressEn?: T;
  addressSq?: T;
  instagram?: T;
  facebook?: T;
  linkedin?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}